name: Cross Compile microsocks

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - { arch: x86_64,         gcc: gcc,                         ext: "" }
          - { arch: alpine-x86_64,  gcc: musl-gcc,                    ext: "" }
          - { arch: armv7,          gcc: arm-linux-gnueabihf-gcc,     ext: "" }
          - { arch: aarch64,        gcc: aarch64-linux-gnu-gcc,       ext: "" }
          - { arch: riscv64,        gcc: riscv64-linux-gnu-gcc,       ext: "" }
          - { arch: s390x,          gcc: s390x-linux-gnu-gcc,         ext: "" }

    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2

    - name: Install cross-compilers
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          musl-tools \
          gcc-arm-linux-gnueabihf \
          gcc-aarch64-linux-gnu \
          gcc-riscv64-linux-gnu \
          gcc-s390x-linux-gnu \
          make

    - name: Clean and Build microsocks for ${{ matrix.target.arch }}
      run: |
        make clean || true
        make CC="${{ matrix.target.gcc }}" STRIP="true"
        mkdir -p dist
        mv microsocks dist/microsocks-${{ matrix.target.arch }}${{ matrix.target.ext }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: microsocks-${{ matrix.target.arch }}
        path: dist/microsocks-${{ matrix.target.arch }}${{ matrix.target.ext }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4.3.0
      with:
        path: artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.2.2
      with:
        files: artifacts/**/*